### ISSUE TITLE
Maquette compte utilisateur connecté

### ISSUE THREAD

**Issue by MelanieRAPHAEL** [mission-apprentissage/partage-simplifie#100]
Revoir la maquette du compte utilisateur connecté : 
- gros blocs avant d'arriver aux infos importantes et au dépôt de fichier
- bouton anomalie qui semble porter sur le type de fichier

**Comment by cathbaiona** [comment]
<img width="548" alt="Capture d’écran 2022-09-29 à 13 02 12" src="https://user-images.githubusercontent.com/108516993/193014893-ff719404-fc1b-43f2-8a16-c25171aaee3c.png">

**Comment by MelanieRAPHAEL** [comment]
@sbenfares

**Comment by MelanieRAPHAEL** [comment]
Pour ce MVP ça me parait bien - ok pour moi 

Je te laisse revoir Catherine si c'est ok pour toi niveau maquette 
ça te va si on revoit un peu en V2 @cathbaiona avec les retours utilisateurs 
(par exemple prévoir, il y a eu des modifs sur mon rôle, ou mon mail, ou je en sais pas, ce qui ressortira, puis une étape de post du fichier sans avoir à scroller, ... bref à voir en V2) 

Si ok pour toi @cathbaiona je te laisse glisser en "déployer en production"

**Comment by sbenfares** [comment]
@MelanieRAPHAEL @cathbaiona correction "Ajout de l'adresse" déployé en recette.
Vous pouvez checker et me dire si OK pour vous.
Testable avec jean@cfa.fr et / ou création d'un nouveau compte OF.
