### ISSUE TITLE
XLSX -  MAJ

### ISSUE THREAD

**Issue by MelanieRAPHAEL** [mission-apprentissage/partage-simplifie#125]
Mettre à jour le CSV avec les nouveaux cas rupturants etc

**Comment by MelanieRAPHAEL** [comment]
@cathbaiona comme tu as les entretiens utilisateurs et sprint chargé, je me mets dessus pour une première passe et je te le passe ensuite

**Comment by MelanieRAPHAEL** [comment]
Carte nouvelles données : https://github.com/mission-apprentissage/partage-simplifie/issues/113

**Comment by MelanieRAPHAEL** [comment]
[PartageSimplifie_ModeleDepotDeDonnees_MAJMEL_1210.xlsx](https://github.com/mission-apprentissage/partage-simplifie/files/9764909/PartageSimplifie_ModeleDepotDeDonnees_MAJMEL_1210.xlsx)

**Comment by cathbaiona** [comment]
<img width="117" alt="Capture d’écran 2022-10-12 à 15 18 44" src="https://user-images.githubusercontent.com/108516993/195353269-c53daa58-36bb-422d-9b7a-4fd8482d275f.png">
Il faudrait mettre Code Formation Diplôme. CFD porte à confusion, et le commentaire n'est pas toujours regardé par les utilisatrices.

**Comment by cathbaiona** [comment]
j'aurai mis les champs en **bold** et en rouge, même si ils peuvent parfois ne pas être remplis.
<img width="698" alt="Capture d’écran 2022-10-12 à 15 24 20" src="https://user-images.githubusercontent.com/108516993/195354544-3a20bd23-edf0-4aaa-9086-4743fed9518a.png">

**Comment by cathbaiona** [comment]
<img width="497" alt="Capture d’écran 2022-10-12 à 15 36 28" src="https://user-images.githubusercontent.com/108516993/195357283-71f9ba9c-29e6-428b-96bb-cc5e338dfba3.png">
Garde-t-on vraiment la mention "date d'abandon et de départ de l'OF" ??

**Comment by sbenfares** [comment]
Ok pour moi j'ai changé le format des dates : 
[PartageSimplifie_ModeleDepotDeDonnees_MAJSBS_1210.xlsx](https://github.com/mission-apprentissage/partage-simplifie/files/9765658/PartageSimplifie_ModeleDepotDeDonnees_MAJSBS_1210.xlsx)

**Comment by sbenfares** [comment]
Voici la nouvelle version avec le format des colonnes Excel + correctif mail disney

@MelanieRAPHAEL @cathbaiona OK Pour vous ?

[PartageSimplifie_ModeleDepotDeDonnees_MAJSBS_1710.xlsx](https://github.com/mission-apprentissage/partage-simplifie/files/9818490/PartageSimplifie_ModeleDepotDeDonnees_MAJSBS_1710.xlsx)

**Comment by cathbaiona** [comment]
Pourras-tu mettre "Code Formation Diplôme" à la place de CFD ? @sbenfares

**Comment by sbenfares** [comment]
Corrigé ici, ok pour vous ?

[PartageSimplifie_ModeleDepotDeDonnees_MAJSBS_1710-2.xlsx](https://github.com/mission-apprentissage/partage-simplifie/files/9818859/PartageSimplifie_ModeleDepotDeDonnees_MAJSBS_1710-2.xlsx)
