### ISSUE TITLE
Cas d'erreur avec les nouvelles données - DÉV

### ISSUE THREAD

**Issue by MelanieRAPHAEL** [mission-apprentissage/partage-simplifie#126]
Prévoir les nouveaux cas d'erreur avec les nouvelles dates collectées 

Reformulation des cas d'erreurs sur les dates : 

- [x] Date inscription obligatoire
- [x] Si Date Début Contrat remplie alors Date de fin de contrat obligatoire
- [x] Si Date Début Contrat et Date de Fin contrat remplies alors Date de Fin de contrat > Date Début
- [x] Si Date Rupture Contrat remplie alors Date de Début de contrat obligatoire
- [x] Si Date Rupture Contrat remplie alors Date de Fin  de contrat obligatoire
- [x] Si Date Rupture Contrat remplie alors doit être > Date Inscription
- [x] Si Date Rupture Contrat remplie alors doit être > Date Début Contrat
- [x] Si Date Rupture Contrat remplie alors doit être < Date Fin Contrat
- [x] Si Date Sortie remplie alors Date de Rupture obligatoire
- [x] Si Date Sortie remplie alors doit être > Date inscription 
- [x] Si Date Sortie remplie alors doit être > Date début contrat

DEV : 

- [x] Update du model nouvelles dates
- [x] Validation cas d'erreurs
- [x] Update tests
- [x] Transformation TdB
- [x] UI Messages

**Comment by MelanieRAPHAEL** [comment]
@sbenfares as-tu besoin de maquettes pour cela ?

**Comment by sbenfares** [comment]
> @sbenfares as-tu besoin de maquettes pour cela ?

Non y'a rien coté UI c'est uniquement la donnée qui change.

**Comment by MelanieRAPHAEL** [comment]
ok j'ajoute une carte pour Catherine
