### ISSUE TITLE
Correction erreurs de Kedge BS

### ISSUE THREAD

**Issue by sbenfares** [mission-apprentissage/partage-simplifie#131]
@cathbaiona en attente des fichiers de Kedge BS

**Comment by sbenfares** [comment]
@cathbaiona besoin de faire un point avec toi car le fichier fourni ne correspond pas au modèle

**Comment by cathbaiona** [comment]
@sbenfares Je suis disponible entre 15 et 16 cet après-midi :)

**Comment by sbenfares** [comment]
@cathbaiona Mes premières remarques : 

- Ils ont laissé les 2 lignes Mickey et Minnie dans le fichier, ces 2 lignes posent problèmes à cause du mail (cf. mon message Slack) 
-> Problème corrigé en modifiant le XLSX

**Comment by sbenfares** [comment]
J'ai corrigé le fichier XLSX et ajouté la gestion des format dates jj/mm/aaaa.
Pour l'erreur sur l'année de formation c'est normal on attends un chiffre.
