### ISSUE TITLE
Espace CFA - Téléchargement du modèle

### ISSUE THREAD

**Issue by sbenfares** [mission-apprentissage/partage-simplifie#8]
- [ ] Récupération du CSV modèle et upload FTP AlwaysData
- [ ] Update UI

**Comment by sbenfares** [comment]
En attente du fichier modèle qui sera fourni par @cathbaiona et @MelanieRAPHAEL

**Comment by sbenfares** [comment]
Fichier proposé : 

[PartageSimplifie_ModeleDepotDeDonnees.xlsx](https://github.com/mission-apprentissage/partage-simplifie/files/9626378/PartageSimplifie_ModeleDepotDeDonnees.xlsx)

**Comment by cathbaiona** [comment]
très propre, ce fichier Excel, il donne envie !

**Comment by MelanieRAPHAEL** [comment]
@sbenfares il y a un nom qui apparait au survol des bulles, possible d'anonymiser ou d'y mettre un compte Beta ? en version MVP pas forcément gênant, mais tu sais si on peut y mettre en changeant sans doute le nom de la personne qui commente en un mail tdb ?

**Comment by sbenfares** [comment]
> @sbenfares il y a un nom qui apparait au survol des bulles, possible d'anonymiser ou d'y mettre un compte Beta ? en version MVP pas forcément gênant, mais tu sais si on peut y mettre en changeant sans doute le nom de la personne qui commente en un mail tdb ?
> 
> C'est non bloquant pour la MEP mais je crée une carte

Besoin de précisions, au survol de quelles bulles stp ?

**Comment by cathbaiona** [comment]
Il s'agit des bulles de commentaires sur les noms des champs. il est indiqué "Catherine Louis"
<img width="429" alt="Capture d’écran 2022-09-27 à 09 56 23" src="https://user-images.githubusercontent.com/108516993/192467670-dc546093-7ce8-4ef8-a196-74a058e574ac.png">

**Comment by sbenfares** [comment]
Je n'arrive pas à le reproduire.

![image](https://user-images.githubusercontent.com/18660099/192472287-2564918e-e894-4729-bba2-0a2d94552a15.png)


N'est-ce pas le nom de l'utilisateur du logiciel plutôt ? 
Vous utilisez Excel ou autre chose ?

**Comment by sbenfares** [comment]
Update du fichier car j'avais des soucis de format, j'ai tout mis en "texte" 👇 



[PartageSimplifie_ModeleDepotDeDonnees.xlsx](https://github.com/mission-apprentissage/partage-simplifie/files/9657330/PartageSimplifie_ModeleDepotDeDonnees.xlsx)
